# Generated by Django 4.2.7 on 2023-12-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_accessories_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
